Traceback (most recent call last):
  File "/data/afatehi/.penvs/venv-gbm/lib/python3.9/site-packages/pudb/__init__.py", line 148, in runscript
    dbg._runscript(mainpyfile)
  File "/data/afatehi/.penvs/venv-gbm/lib/python3.9/site-packages/pudb/debugger.py", line 519, in _runscript
    self.run(statement)
  File "/opt/conda/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "labels_merge.py", line 43, in <module>
    json.dump(tif_tags, fp)
  File "/opt/conda/lib/python3.9/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/conda/lib/python3.9/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/conda/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/conda/lib/python3.9/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/conda/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
